{
 "title": "JDownloader",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(jdownloader_download_speed, device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdownloader_download_speed{device_name=\"pils\"}"
    }
   ]
  },
  {
   "title": "Download Packages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdownloader_download_package_count{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Packages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdownloader_linkgrabber_package_count{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jdownloader_download_speed{device_name=\"pils\"}"
    }
   ]
  },
  {
   "title": "Bytes remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdownloader_total_bytes_to_download{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue total size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdownloader_total_bytes_to_download{device_name=~\"$device_name\"} + jdownloader_total_bytes_in_linkgrabber{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jdownloader_total_bytes_downloaded{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue remaining total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jdownloader_total_bytes_to_download{device_name=~\"$device_name\"} + jdownloader_total_bytes_in_linkgrabber{device_name=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}